apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nenlo7c6d-dotnet-basic
  janus-idp.io/tekton: nenlo7c6d-dotnet-basic
  backstage.io/kubernetes-id: nenlo7c6d-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nenlo7c6d-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
